import { Metadata } from "next";
import { getSiteMetadata, getSiteRegulars, getCmsSchemaEntries, findPackageCategory } from "./data";
import { PageMetaKey } from "@/types/metadata";
import { SITE_URL, site, contact, address, business, links } from "@/config/site";

/**
 * Builds a complete Next.js `Metadata` object for any page.
 *
 * @param pageKey  - "home" reads `home_meta`; any other key reads `pages_meta[pageKey]`
 * @param overrides - Partial<Metadata> merged on top (page-level values win)
 * @param pathSegment - URL path, e.g. "/rooms". Used to generate the canonical URL.
 *
 * @example — static page
 *   export async function generateMetadata(): Promise<Metadata> {
 *     return buildMetadata("rooms", {}, "/rooms");
 *   }
 *
 * @example — dynamic page with page-specific title override
 *   return buildMetadata("rooms", { title: room.title }, `/rooms/${slug}`);
 */
export async function buildMetadata(
  pageKey: PageMetaKey | string,
  overrides: Partial<Metadata> = {},
  pathSegment: string = ""
): Promise<Metadata> {
  const meta = await getSiteMetadata();

  let faviconUrl = "/logo.png";
  try {
    const siteRegulars = await getSiteRegulars();
    const favIcon = siteRegulars?.fav_icon;
    const logoUpload = siteRegulars?.logo_upload;
    if (typeof favIcon === "string" && favIcon) {
      faviconUrl = favIcon;
    } else if (typeof logoUpload === "string" && logoUpload) {
      faviconUrl = logoUpload;
    }
  } catch {
    // noop
  }

  // Resolve the per-page meta block
  const pageMeta = pageKey === "home" ? meta.home_meta : (meta.pages_meta ?? {})[pageKey];

  const title = pageMeta?.meta_title ?? meta.site?.title ?? site.title;

  const description = pageMeta?.meta_description ?? meta.site?.title ?? site.description;

  const keywords = pageMeta?.meta_keywords ?? site.keywords;

  const ogImage = meta.social?.fb_img ?? meta.social?.x_img ?? "";
  const ogType = (meta.social?.og_type as "website" | "article") ?? "website";

  // robots: default to index + follow, respect API override
  const robotsApi = meta.scripts?.robots;
  const robots: Metadata["robots"] = {
    index: robotsApi?.index ?? true,
    follow: robotsApi?.follow ?? true,
    googleBot: {
      index: robotsApi?.index ?? true,
      follow: robotsApi?.follow ?? true,
    },
  };

  // Canonical URL — always generated by us (CMS value is intentionally empty)
  const canonical = pathSegment ? `${SITE_URL}${pathSegment}` : undefined;

  const base: Metadata = {
    metadataBase: new URL(SITE_URL),
    title,
    description,
    keywords,
    robots,
    icons: {
      icon: faviconUrl,
    },
    ...(canonical && { alternates: { canonical } }),
    openGraph: {
      title,
      description,
      type: ogType,
      ...(canonical && { url: canonical }),
      siteName: meta.site?.name ?? site.name,
      ...(ogImage && { images: [{ url: ogImage }] }),
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      ...(meta.social?.x_img && { images: [meta.social.x_img] }),
    },
  };

  // Deep-merge overrides: openGraph fields require special handling
  const { openGraph: ogOverride, twitter: twOverride, ...restOverrides } = overrides;

  return {
    ...base,
    ...restOverrides,
    openGraph: {
      ...base.openGraph,
      ...(ogOverride ?? {}),
    },
    twitter: {
      ...base.twitter,
      ...(twOverride ?? {}),
    },
  };
}

/**
 * Metadata for a /rooms, /dining, /events listing page: same "look up the
 * `package` category record, let its meta_title/meta_description override
 * the generic page defaults" logic each of those pages used to repeat.
 */
export async function buildCategoryListingMetadata(
  pageKey: PageMetaKey,
  categoryId: string,
  pathSegment: string
): Promise<Metadata> {
  const category = await findPackageCategory(categoryId);
  const overrides: Partial<Metadata> = {};
  if (category?.meta_title) overrides.title = category.meta_title;
  if (category?.meta_description) overrides.description = category.meta_description;
  return buildMetadata(pageKey, overrides, pathSegment);
}

/**
 * Builds a LodgingBusiness/Hotel + WebSite JSON-LD schema from the site
 * metadata. Used once in the root layout.
 */
export async function buildOrganizationSchema(): Promise<Record<string, unknown>[]> {
  const meta = await getSiteMetadata();
  const ogImage = meta.social?.fb_img ?? meta.social?.x_img ?? "";

  const organization: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": [...site.schemaType],
    name: meta.site?.name ?? site.name,
    alternateName: site.shortName,
    url: SITE_URL,
    description: meta.home_meta?.meta_description ?? site.description,
    telephone: contact.phone,
    email: contact.email,
    priceRange: business.priceRange,
    starRating: { "@type": "Rating", ratingValue: String(business.starRating) },
    // Only emit aggregateRating when real, on-page-verifiable numbers are set.
    ...(business.aggregateRating && {
      aggregateRating: { "@type": "AggregateRating", ...business.aggregateRating },
    }),
    address: {
      "@type": "PostalAddress",
      streetAddress: address.street,
      addressLocality: address.locality,
      addressRegion: address.region,
      postalCode: address.postalCode,
      addressCountry: address.country,
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: address.geo.latitude,
      longitude: address.geo.longitude,
    },
    hasMap: address.mapUrl,
    checkinTime: business.checkinTime,
    checkoutTime: business.checkoutTime,
    numberOfRooms: business.numberOfRooms,
    amenityFeature: business.amenities.map((name) => ({
      "@type": "LocationFeatureSpecification",
      name,
      value: true,
    })),
    contactPoint: {
      "@type": "ContactPoint",
      telephone: contact.phone,
      contactType: "reservations",
      availableLanguage: business.languages,
    },
    openingHoursSpecification: {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
      opens: "00:00",
      closes: "23:59",
    },
    ...(ogImage && { image: ogImage }),
    sameAs: links.social,
  };

  // No site search exists yet, so no WebSite.potentialAction/SearchAction —
  // that schema requires a real, working search URL behind it.
  const webSite: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: meta.site?.name ?? site.name,
    url: SITE_URL,
  };

  return [organization, webSite];
}

// ─────────────────────────────────────────────────────────────────────────────
// CMS Schema API integration
// ─────────────────────────────────────────────────────────────────────────────

interface CmsSchemaEntry {
  id?: string;
  title?: string;
  slug?: string;
  schema_code?: string | Record<string, unknown>;
  faq_schema?: { q?: string; a?: string }[];
  image?: string;
  fb_upload?: string;
  meta_title?: string;
  meta_keywords?: string;
  meta_description?: string;
}

/** Strip leading slash: "/rooms" → "rooms", "/" → "" */
function normaliseSlug(s: string): string {
  return s.replace(/^\//, "");
}

/**
 * schema_code arrives as a full <script type="application/ld+json">…</script>
 * HTML string. This extracts the JSON inside, fixes trailing commas that
 * the CMS editor sometimes produces, and returns a parsed object.
 */
function parseSchemaCode(raw: string | Record<string, unknown>): Record<string, unknown> | null {
  if (!raw) return null;

  if (typeof raw === "object") return raw;

  const str = raw.trim();
  const match = str.match(/<script[^>]*>([\s\S]*?)<\/script>/i);
  const jsonStr = match ? match[1].trim() : str;

  if (!jsonStr.startsWith("{") && !jsonStr.startsWith("[")) return null;

  const cleaned = jsonStr.replace(/,(\s*[}\]])/g, "$1");

  try {
    return JSON.parse(cleaned) as Record<string, unknown>;
  } catch {
    return null;
  }
}

/**
 * Fetches the CMS `schema` endpoint and returns JSON-LD objects.
 *
 * Entries with an empty/null slug are global; entries with a slug belong to
 * that one page. The `scope` selects which set to return:
 *   - "global" → only slug-less entries  (injected once in the root layout)
 *   - "page"   → only entries whose slug matches `currentPath`  (per-page)
 *   - "all"    → both  (legacy behaviour)
 */
export async function buildCmsSchemas(
  currentPath = "/",
  scope: "all" | "global" | "page" = "all"
): Promise<Record<string, unknown>[]> {
  const entries = await getCmsSchemaEntries<CmsSchemaEntry>();

  const page = normaliseSlug(currentPath);

  const relevant = entries.filter((entry) => {
    const isGlobal = !entry.slug;
    if (scope === "global") return isGlobal;
    if (scope === "page") return !isGlobal && normaliseSlug(entry.slug!) === page;
    return isGlobal || normaliseSlug(entry.slug!) === page;
  });

  const schemas: Record<string, unknown>[] = [];

  for (const entry of relevant) {
    if (!entry.schema_code) continue;
    const parsed = parseSchemaCode(entry.schema_code);
    if (parsed) schemas.push(parsed);
  }

  const faqs: { q: string; a: string }[] = [];
  for (const entry of relevant) {
    if (!Array.isArray(entry.faq_schema)) continue;
    for (const item of entry.faq_schema) {
      const q = item.q?.trim();
      const a = item.a?.trim();
      if (q && a) faqs.push({ q, a });
    }
  }

  if (faqs.length > 0) {
    schemas.push({
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: faqs.map(({ q, a }) => ({
        "@type": "Question",
        name: q,
        acceptedAnswer: { "@type": "Answer", text: a },
      })),
    });
  }

  return schemas;
}

/**
 * Builds JSON-LD for a parent-category landing page from its `package` record.
 * Only emits an FAQPage from `faq_schema`; returns [] when there are none.
 */
export function buildPackageSchemas(
  pkg: { faq_schema?: { q?: string; a?: string }[] } | null | undefined
): Record<string, unknown>[] {
  if (!pkg || !Array.isArray(pkg.faq_schema)) return [];

  const faqs: { q: string; a: string }[] = pkg.faq_schema
    .map((item) => ({ q: item.q?.trim(), a: item.a?.trim() }))
    .filter((item): item is { q: string; a: string } => Boolean(item.q && item.a));

  if (faqs.length === 0) return [];

  return [
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: faqs.map(({ q, a }) => ({
        "@type": "Question",
        name: q,
        acceptedAnswer: { "@type": "Answer", text: a },
      })),
    },
  ];
}
